apiVersion: v1
kind: Service
metadata:
  name: spring-app
spec:
  selector:
    app: spring-app
  ports:
    - protocol: TCP
      port: 8082        # Port on the Service
      targetPort: 8082  # Port on the container
  type: LoadBalancer    # or ClusterIP / NodePort as needed
